package io.polyglotted.pgmodel.ac;

@SuppressWarnings("unused")
public enum SubjectAttribute {
    CREDENTIAL, ACCESS_TOKEN, FIRST_NAME, LAST_NAME, DISPLAY_NAME, EMAIL, COUNTRY, DESCRIPTION, DEPARTMENT,
    GROUPS, ROLES, PHONE, TIMESTAMP, API_REF, RESOURCE, IP_ADDRESS, RPC_ID, PUBLIC_KEY, TRUSTED
}
